export type appleMusicRanking = {
  name: string;
  nameKorean: string;
  icon: string;
};

export const appleMusicRankings: appleMusicRanking[] = [
  { name: "global", nameKorean: "글로벌", icon: "🌏" },
  { name: "antigua-and-barbuda", nameKorean: "앤티가 바부다", icon: "🇦🇬" },
  { name: "argentina", nameKorean: "아르헨티나", icon: "🇦🇷" },
  { name: "armenia", nameKorean: "아르메니아", icon: "🇦🇲" },
  { name: "austria", nameKorean: "오스트리아", icon: "🇦🇺" },
  { name: "azerbaijan", nameKorean: "아제르바이잔", icon: "🇦🇿" },
  { name: "bahrain", nameKorean: "바레인", icon: "🇧🇭" },
  { name: "barbados", nameKorean: "바베이도스", icon: "🇧🇧" },
  { name: "belarus", nameKorean: "벨라루스", icon: "🇧🇾" },
  { name: "belgium", nameKorean: "벨기에", icon: "🇧🇪" },
  { name: "belize", nameKorean: "벨리즈", icon: "🇧🇧" },
  { name: "bolivia", nameKorean: "볼리비아", icon: "🇧🇴" },
  { name: "botswana", nameKorean: "보츠와나", icon: "🇧🇼" },
  { name: "brazil", nameKorean: "브라질", icon: "🇧🇷" },
  { name: "bulgaria", nameKorean: "불가리아", icon: "🇧🇬" },
  { name: "cambodia", nameKorean: "캄보디아", icon: "🇰🇭" },
  { name: "cape-verde", nameKorean: "카보베르데", icon: "🇨🇻" },
  { name: "chile", nameKorean: "칠레", icon: "🇨🇱" },
  { name: "china", nameKorean: "중국", icon: "🇨🇳" },
  { name: "colombia", nameKorean: "콜롬비아", icon: "🇨🇴" },
  { name: "costa-rica", nameKorean: "코스타리카", icon: "🇨🇷" },
  { name: "cyprus", nameKorean: "키프로스", icon: "🇨🇾" },
  { name: "czechia", nameKorean: "체코", icon: "🇨🇿" },
  { name: "denmark", nameKorean: "덴마크", icon: "🇩🇰" },
  { name: "dominica", nameKorean: "도미니카", icon: "🇩🇲" },
  { name: "dominican-republic", nameKorean: "도미니카 공화국", icon: "🇩🇴" },
  { name: "ecuador", nameKorean: "에콰도르", icon: "🇪🇨" },
  { name: "egypt", nameKorean: "이집트", icon: "🇪🇬" },
  { name: "el-salvador", nameKorean: "엘살바도르", icon: "🇸🇻" },
  { name: "estonia", nameKorean: "에스토니아", icon: "🇪🇪" },
  { name: "eswatini", nameKorean: "에스와티니", icon: "🇸🇿" },
  { name: "fiji", nameKorean: "피지", icon: "🇫🇯" },
  { name: "finland", nameKorean: "핀란드", icon: "🇫🇮" },
  { name: "france", nameKorean: "프랑스", icon: "🇫🇷" },
  { name: "gambia", nameKorean: "감비아", icon: "🇬🇲" },
  { name: "germany", nameKorean: "독일", icon: "🇩🇪" },
  { name: "ghana", nameKorean: "가나", icon: "🇬🇭" },
  { name: "greece", nameKorean: "그리스", icon: "🇬🇷" },
  { name: "grenada", nameKorean: "그레나다", icon: "🇬🇩" },
  { name: "guatemala", nameKorean: "과테말라", icon: "🇬🇹" },
  { name: "guinea-bissau", nameKorean: "기니비사우", icon: "🇬🇼" },
  { name: "honduras", nameKorean: "온두라스", icon: "🇭🇳" },
  { name: "hong-kong", nameKorean: "홍콩", icon: "🇭🇰" },
  { name: "hungary", nameKorean: "헝가리", icon: "🇭🇺" },
  { name: "india", nameKorean: "인도", icon: "🇮🇳" },
  { name: "indonesia", nameKorean: "인도네시아", icon: "🇮🇩" },
  { name: "israel", nameKorean: "이스라엘", icon: "🇮🇱" },
  { name: "italy", nameKorean: "이탈리아", icon: "🇮🇹" },
  { name: "japan", nameKorean: "일본", icon: "🇯🇵" },
  { name: "jordan", nameKorean: "요르단", icon: "🇯🇴" },
  { name: "kazakhstan", nameKorean: "카자흐스탄", icon: "🇰🇿" },
  { name: "kenya", nameKorean: "케냐", icon: "🇰🇪" },
  { name: "kyrgyzstan", nameKorean: "키르기스스탄", icon: "🇰🇬" },
  { name: "laos", nameKorean: "라오스", icon: "🇱🇦" },
  { name: "latvia", nameKorean: "라트비아", icon: "🇱🇻" },
  { name: "lebanon", nameKorean: "레바논", icon: "🇱🇧" },
  { name: "lithuania", nameKorean: "리투아니아", icon: "🇱🇹" },
  { name: "luxembourg", nameKorean: "룩셈부르크", icon: "🇱🇺" },
  { name: "malaysia", nameKorean: "말레이시아", icon: "🇲🇾" },
  { name: "malta", nameKorean: "몰타", icon: "🇲🇹" },
  { name: "mauritius", nameKorean: "모리셔스", icon: "🇲🇺" },
  { name: "mexico", nameKorean: "멕시코", icon: "🇲🇽" },
  { name: "mongolia", nameKorean: "몽골", icon: "🇲🇳" },
  { name: "nepal", nameKorean: "네팔", icon: "🇳🇵" },
  { name: "netherlands", nameKorean: "네덜란드", icon: "🇳🇱" },
  { name: "new-zealand", nameKorean: "뉴질랜드", icon: "🇳🇿" },
  { name: "nicaragua", nameKorean: "니카라과", icon: "🇳🇮" },
  { name: "niger", nameKorean: "니제르", icon: "🇳🇪" },
  { name: "nigeria", nameKorean: "나이지리아", icon: "🇳🇬" },
  { name: "norway", nameKorean: "노르웨이", icon: "🇳🇴" },
  { name: "oman", nameKorean: "오만", icon: "🇴🇲" },
  { name: "panama", nameKorean: "파나마", icon: "🇵🇦" },
  { name: "papua-new-guinea", nameKorean: "파푸아뉴기니", icon: "🇵🇬" },
  { name: "paraguay", nameKorean: "파라과이", icon: "🇵🇾" },
  { name: "peru", nameKorean: "페루", icon: "🇵🇪" },
  { name: "philippines", nameKorean: "필리핀", icon: "🇵🇭" },
  { name: "poland", nameKorean: "폴란드", icon: "🇵🇱" },
  { name: "portugal", nameKorean: "포르투갈", icon: "🇵🇹" },
  { name: "moldova", nameKorean: "몰도바", icon: "🇲🇩" },
  { name: "romania", nameKorean: "루마니아", icon: "🇷🇴" },
  { name: "saudi-arabia", nameKorean: "사우디아라비아", icon: "🇸🇦" },
  { name: "singapore", nameKorean: "싱가포르", icon: "🇸🇬" },
  { name: "slovakia", nameKorean: "슬로바키아", icon: "🇸🇰" },
  { name: "slovenia", nameKorean: "슬로베니아", icon: "🇸🇮" },
  { name: "south-africa", nameKorean: "남아프리카 공화국", icon: "🇿🇦" },
  { name: "south-korea", nameKorean: "대한민국", icon: "🇰🇷" },
  { name: "sri-lanka", nameKorean: "스리랑카", icon: "🇱🇰" },
  { name: "st-kitts-and-nevis", nameKorean: "세인트키츠 네비스", icon: "🇰🇳" },
  { name: "sweden", nameKorean: "스웨덴", icon: "🇸🇪" },
  { name: "switzerland", nameKorean: "스위스", icon: "🇨🇭" },
  { name: "taiwan", nameKorean: "대만", icon: "🇹🇼" },
  { name: "tajikistan", nameKorean: "타지키스탄", icon: "🇹🇯" },
  { name: "thailand", nameKorean: "태국", icon: "🇹🇭" },
  { name: "trinidad-and-tobago", nameKorean: "트리니다드 토바고", icon: "🇹🇹" },
  { name: "turkmenistan", nameKorean: "투르크메니스탄", icon: "🇹🇲" },
  { name: "uganda", nameKorean: "우간다", icon: "🇺🇬" },
  { name: "uk", nameKorean: "영국", icon: "🇬🇧" },
  { name: "usa", nameKorean: "미국", icon: "🇺🇸" },
  { name: "ukraine", nameKorean: "우크라이나", icon: "🇺🇦" },
  { name: "united-arab-emirates", nameKorean: "아랍에미리트", icon: "🇦🇪" },
  { name: "uzbekistan", nameKorean: "우즈베키스탄", icon: "🇺🇿" },
  { name: "venezuela", nameKorean: "베네수엘라", icon: "🇻🇪" },
  { name: "vietnam", nameKorean: "베트남", icon: "🇻🇳" },
  { name: "zimbabwe", nameKorean: "짐바브웨", icon: "🇿🇼" },
];
