export type spotifyMusicRanking = {
  name: string;
  nameKorean: string;
  icon: string;
};

export const spotifyMusicRankings: spotifyMusicRanking[] = [
  { name: "global", nameKorean: "글로벌", icon: "🌏" },
  { name: "argentina", nameKorean: "아르헨티나", icon: "🇦🇷" },
  { name: "australia", nameKorean: "호주", icon: "🇦🇺" },
  { name: "austria", nameKorean: "오스트리아", icon: "🇦🇹" },
  { name: "belarus", nameKorean: "벨라루스", icon: "🇧🇾" },
  { name: "belgium", nameKorean: "벨기에", icon: "🇧🇪" },
  { name: "bolivia", nameKorean: "볼리비아", icon: "🇧🇴" },
  { name: "brazil", nameKorean: "브라질", icon: "🇧🇷" },
  { name: "bulgaria", nameKorean: "불가리아", icon: "🇧🇬" },
  { name: "canada", nameKorean: "캐나다", icon: "🇨🇦" },
  { name: "chile", nameKorean: "칠레", icon: "🇨🇱" },
  { name: "colombia", nameKorean: "콜롬비아", icon: "🇨🇴" },
  { name: "costa-rica", nameKorean: "코스타리카", icon: "🇨🇷" },
  { name: "czech-republic", nameKorean: "체코", icon: "🇨🇿" },
  { name: "denmark", nameKorean: "덴마크", icon: "🇩🇰" },
  { name: "dominican-republic", nameKorean: "도미니카공화국", icon: "🇩🇴" },
  { name: "ecuador", nameKorean: "에콰도르", icon: "🇪🇨" },
  { name: "egypt", nameKorean: "이집트", icon: "🇪🇬" },
  { name: "el-salvador", nameKorean: "엘살바도르", icon: "🇸🇻" },
  { name: "estonia", nameKorean: "에스토니아", icon: "🇪🇪" },
  { name: "finland", nameKorean: "핀란드", icon: "🇫🇮" },
  { name: "france", nameKorean: "프랑스", icon: "🇫🇷" },
  { name: "germany", nameKorean: "독일", icon: "🇩🇪" },
  { name: "greece", nameKorean: "그리스", icon: "🇬🇷" },
  { name: "guatemala", nameKorean: "과테말라", icon: "🇬🇹" },
  { name: "honduras", nameKorean: "온두라스", icon: "🇭🇳" },
  { name: "hong-kong", nameKorean: "홍콩", icon: "🇭🇰" },
  { name: "hungary", nameKorean: "헝가리", icon: "🇭🇺" },
  { name: "iceland", nameKorean: "아이슬란드", icon: "🇮🇸" },
  { name: "israel", nameKorean: "이스라엘", icon: "🇮🇱" },
  { name: "italy", nameKorean: "이탈리아", icon: "🇮🇹" },
  { name: "japan", nameKorean: "일본", icon: "🇯🇵" },
  { name: "kazakhstan", nameKorean: "카자흐스탄", icon: "🇰🇿" },
  { name: "latvia", nameKorean: "라트비아", icon: "🇱🇻" },
  { name: "lithuania", nameKorean: "리투아니아", icon: "🇱🇹" },
  { name: "luxembourg", nameKorean: "룩셈부르크", icon: "🇱🇺" },
  { name: "malaysia", nameKorean: "말레이시아", icon: "🇲🇾" },
  { name: "mexico", nameKorean: "멕시코", icon: "🇲🇽" },
  { name: "morocco", nameKorean: "모로코", icon: "🇲🇦" },
  { name: "netherlands", nameKorean: "네덜란드", icon: "🇳🇱" },
  { name: "new-zealand", nameKorean: "뉴질랜드", icon: "🇳🇿" },
  { name: "nicaragua", nameKorean: "니카라과", icon: "🇳🇮" },
  { name: "norway", nameKorean: "노르웨이", icon: "🇳🇴" },
  { name: "pakistan", nameKorean: "파키스탄", icon: "🇵🇰" },
  { name: "panama", nameKorean: "파나마", icon: "🇵🇦" },
  { name: "paraguay", nameKorean: "파라과이", icon: "🇵🇾" },
  { name: "peru", nameKorean: "페루", icon: "🇵🇪" },
  { name: "philippines", nameKorean: "필리핀", icon: "🇵🇭" },
  { name: "poland", nameKorean: "폴란드", icon: "🇵🇱" },
  { name: "portugal", nameKorean: "포르투갈", icon: "🇵🇹" },
  { name: "romania", nameKorean: "루마니아", icon: "🇷🇴" },
  { name: "saudi-arabia", nameKorean: "사우디아라비아", icon: "🇸🇦" },
  { name: "singapore", nameKorean: "싱가포르", icon: "🇸🇬" },
  { name: "slovakia", nameKorean: "슬로바키아", icon: "🇸🇰" },
  { name: "south-africa", nameKorean: "남아프리카", icon: "🇿🇦" },
  { name: "south-korea", nameKorean: "대한민국", icon: "🇰🇷" },
  { name: "spain", nameKorean: "스페인", icon: "🇪🇸" },
  { name: "sweden", nameKorean: "스웨덴", icon: "🇸🇪" },
  { name: "switzerland", nameKorean: "스위스", icon: "🇨🇭" },
  { name: "taiwan", nameKorean: "대만", icon: "🇹🇼" },
  { name: "thailand", nameKorean: "태국", icon: "🇹🇭" },
  { name: "turkey", nameKorean: "터키", icon: "🇹🇷" },
  { name: "united-arab-emirates", nameKorean: "아랍에미리트", icon: "🇦🇪" },
  { name: "ukraine", nameKorean: "우크라이나", icon: "🇺🇦" },
  { name: "uk", nameKorean: "영국", icon: "🇬🇧" },
  { name: "uruguay", nameKorean: "우루과이", icon: "🇺🇾" },
  { name: "usa", nameKorean: "미국", icon: "🇺🇸" },
  { name: "venezuela", nameKorean: "베네수엘라", icon: "🇻🇪" },
  { name: "vietnam", nameKorean: "베트남", icon: "🇻🇳" },
];
